apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-cert
  namespace: istio-system
spec:
  secretName: petclinic-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - spring-petclinic.antoanso.dev
  - '*.spring-petclinic.antoanso.dev'
