{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "petclinic.fullname" (dict "name" (printf "%s-sa" $name) "context" $) }}
  labels:
    {{- include "petclinic.labels" $ | nindent 4 }}
    app: {{ include "petclinic.name" $ }}
    service: {{ $name }}
{{- if $svc.serviceAccount }}
{{- if $svc.serviceAccount.annotations }}
  annotations:
    {{- toYaml $svc.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
