{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" (dict "name" $name "context" $) }}
  labels:
    {{- include "petclinic.labels" $ | nindent 4 }}
    app: {{ include "petclinic.name" $ }}
    service: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "petclinic.name" $ }}
    service: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      nodePort: {{ $svc.nodePort }}
---
{{- end }}
{{- end }}
