apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
  namespace: spring-petclinic
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: terrytantan/spring-petclinic-admin-server:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s