apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-petclinic-ingress
  namespace: spring-petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: admin.spring-petclinic.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: admin-server
              port:
                number: 9090
    - host: spring-petclinic.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-gateway
              port:
                number: 8080
    - host: discovery.spring-petclinic.com
      http:
        paths:  
        - path: /
          pathType: Prefix
          backend:
            service:
              name: discovery-server
              port:
                number: 8761
    - host: config.spring-petclinic.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: config-server
              port:
                number: 8888