apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: spring-petclinic
  labels:
    app: genai-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  selector:
    app: genai-service