global:
  imagePrefix: asia-southeast1-docker.pkg.dev/servicemesh-481417/service-mesh
  tag: "latest"
  imagePullPolicy: Always

services:
  config-server:
    enabled: true
    image: spring-petclinic-config-server
    port: 8888
    replicas: 1

  discovery-server:
    enabled: true
    image: spring-petclinic-discovery-server
    port: 8761
    replicas: 1

  customers-service:
    enabled: true
    image: spring-petclinic-customers-service
    port: 8081
    replicas: 1

  visits-service:
    enabled: true
    image: spring-petclinic-visits-service
    port: 8082
    replicas: 1

  vets-service:
    enabled: true
    image: spring-petclinic-vets-service
    port: 8083
    replicas: 1

  genai-service:
    enabled: true
    image: spring-petclinic-genai-service
    port: 8084
    replicas: 1
    env:
      OPENAI_API_KEY: ""
      AZURE_OPENAI_KEY: ""
      AZURE_OPENAI_ENDPOINT: ""

  api-gateway:
    enabled: true
    image: spring-petclinic-api-gateway
    port: 8080
    replicas: 1

  admin-server:
    enabled: true
    image: spring-petclinic-admin-server
    port: 9090
    replicas: 1

  tracing-server:
    enabled: true
    image: openzipkin/zipkin
    port: 9411
    replicas: 1

  prometheus-server:
    enabled: true
    image: prometheus-server
    port: 9090
    replicas: 1

  grafana-server:
    enabled: true
    image: grafana-server
    port: 3000
    replicas: 1
