apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-server-deployment
  namespace: spring-petclinic
  labels:
    app: customers-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-server
  template:
    metadata:
      labels:
        app: customers-server
    spec:
      containers:
        - name: customers-server
          image: terrytantan/spring-petclinic-customers-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s