apiVersion: v1
kind: Service
metadata:
  name: customers-server-service
  namespace: spring-petclinic
  labels:
    app: customers-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: customers-server