apiVersion: v1
kind: Service
metadata:
  name: vets-server-service
  namespace: spring-petclinic
  labels:
    app: vets-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  selector:
    app: vets-server